spring.application.name=OIDC_provider
server.port=8080

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Render DB connection (使用環境變數覆寫，預設為 external URL)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate


oauth.client.client-id=12345.apps.picusercontent.com
oauth.client.client-secret=0000
endpoint=https://oauth2-demo-provider.onrender.com/api/oauth/authorize
