spring.application.name=OIDC_demo-1
server.port=${PORT:9090}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/member}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# OAuth Client Configuration
oauth.client.client-id=12345.apps.picusercontent.com
oauth.client.client-secret=0000
#oauth.client.authorization-endpoint=http://localhost:4000/oauth/authorize
#oauth.client.token-endpoint=http://localhost:4000/oauth/token
