spring.application.name=OIDC_demo-1
server.port=${PORT:9090}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d51aie95pdvs73cl1ag0-a:5432/oidc_provider}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:8lHZMVXRonqf8BBOSIQTt2W7m7BJM2ec}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# OAuth Client Configuration
oauth.client.client-id=12345.apps.picusercontent.com
oauth.client.client-secret=0000

